[package]
name = "unreact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grass = "0.11.2"
handlebars = "4.3.5"
serde = "1.0.147"
serde_json = "1.0.87"
